/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  ipWhitelist: [
    '127.0.0.1',
    '::ffff:127.0.0.1',
    '::1',
    '::ffff:192.168.0.9/24',
    '192.168.0.9/24'
  ],
  language: 'en',
  modules: [
    {
      module: 'alert',
      config: {}
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {}
    },
    {
      module: 'MMM-Remote-Control',
      config: {}
    },
    {
      module: 'weather',
      position: 'bottom_left',
      header: 'Ballerup',
      config: {
        location: 'Ballerup',
        locationID: '2624341',
        apiKey: 'YOUR_OPENWEATHER_API_KEY',
        showHumidity: true,
        initialLoadDelay: 1500
      }
    },
    {
      module: 'MMM-DynamicWeather',
      position: 'fullscreen_above',
      config: {
        locationID: '2624341',
        api_key: 'YOUR_OPENWEATHER_API_KEY',
        weatherInterval: 300000
      }
    },
    {
      module: 'MMM-WeatherOrNot',
      position: 'bottom_left',
      header: '',
      config: {
        location: 'ballerup',
        locationCode: '55d7212d35',
        languages: 'da',
        tempUnits: 'C',
        font: 'Tahoma',
        textColor: '#eeeeee',
        htColor: '#ffffff',
        ltColor: '#d7d7d7',
        sunColor: '#de792d',
        moonColor: '#eeeeee',
        cloudColor: '#dfdede',
        cloudFill: '#323232',
        rainColor: '#8bc1e5',
        snowColor: '#ffffff',
        height: '210px',
        width: '335px',
        label2: 'Ballerup',
        days: '7',
        theme: 'dark',
        bgColor: '#000000',
        icons: 'Climacons Animated',
        updateInterval: 600000
      }
    },
    {
      module: 'MMM-NewsFeedBT',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'BT',
            url: 'https://www.bt.dk/bt/seneste/rss'
          }
        ]
      }
    },
    {
      module: 'calendar',
      header: 'INSERT YOURS HERE',
      position: 'bottom_left',
      timeFormat: 24,
      config: {
        dateFormat: 'DD MMM YY HH:mm',
        dateEndFormat: 'HH:mm',
        fullDayEventDateFormat: 'DD MMM YY',
        colored: true,
        showLocation: true,
        maximumNumberOfDays: 90,
        maximumEntries: 7,
        calendars: [
          {
            symbol: 'calendar',
            url: 'http://localhost:8080/modules/calendars/INSERT-YOUS-HERE.ics',
            color: '#5bc0de'
          }
        ]
      }
    },
    {
      module: 'calendar',
      header: "INSERT YOURS HERE",
      position: 'bottom_left',
      timeFormat: 24,
      config: {
        dateFormat: 'DD MMM YY HH:mm',
        dateEndFormat: 'HH:mm',
        fullDayEventDateFormat: 'DD MMM YY',
        colored: true,
        showLocation: true,
        maximumNumberOfDays: 90,
        maximumEntries: 7,
        calendars: [
          {
            symbol: 'calendar',
            url: 'http://localhost:8080/modules/calendars/INSERT-YOUS-HERE.ics',
            color: '#5bc0de'
          }
        ]
      }
    },
    {
      module: 'MMM-Formula1',
      position: 'bottom_right',
      header: 'F1 Stilling',
      config: {
	season: "current",
	type: "DRIVER",
	maxRows: 10,
	calendar: false,
	showConstructor: true,
	fade: true,
	fadePoint: 0.3,
	reloadInterval: 1800000,
	animationSpeed: 2500,
	grayscale: true,
	showFooter: true
      }
    },
    {
      module: 'calendar',
      header: 'F1 Kalender',
      position: 'bottom_right',
      timeFormat: 24,
      config: {
        dateFormat: 'DD MMM YY HH:mm',
        dateEndFormat: 'HH:mm',
        fullDayEventDateFormat: 'DD MMM YY',
        colored: true,
        showLocation: true,
        maxRows: 10,
        maximumNumberOfDays: 90,
        maximumEntries: 7,
        calendars: [
          {
            symbol: 'calendar-check',
            url: 'webcal://www.f1calendar.com/download/da/f1-calendar_q_gp.ics?t=1639502383059',
            color: '#FFF000'
          }
        ]
      }
    },
    {
      module: 'MMM-CountDown',
      position: "upper_third",
      config: {
        position: "upper_third",
	   event: "Le Mans 2022 on:",
	   date: "2022-06-11 16:00:00",
	   showHours: true,
	   showMinutes: true,
	   showSeconds: true,
	   customInterval: 1000,
	   daysLabel: 'd',
	   hoursLabel: 't',
	   minutesLabel: 'm',
	   secondsLabel: 's',
      }
    },
    {
      module: 'MMM-NewsFeedEB',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'Ekstra Bladet',
            url: 'https://ekstrabladet.dk/rssfeed/nyheder/'
          }
        ]
      }
    },
    {
      module: 'MMM-DailyPower',
      position: 'middle_center',
      config: {
        translation: 'danish',
        blackAndWhite: false
      }
    },
    {
      module: 'MMM-NewsFeedTV2',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'TV2 Lorry',
            url: 'https://www.tv2lorry.dk/rss'
          }
        ]
      }
    },  
    {
    module: 'MMM-Nagios',
    position: 'top_right',
    header: 'Nagios - Services',
    config: {
      statusUrl: 'https://<YOUR URL>/statusJson.php',
      username:'Basic auth username',
      password: 'Basic auth password',
      showDetails: true,
      showHosts: false
    }
  },
  {
      module: 'MMM-Nagios',
      position: 'top_right',
      header: 'Nagios - Hosts',
      config: {
        statusUrl: 'https://<YOUR URL>/statusJson.php',
        username:'Basic auth username',
        password: 'Basic auth password',
        showDetails: true,
        showHosts: true
      }
    },	  
    {
      module: 'MMM-network-signal',
      position: 'top_right',
      config: {
        animationSpeed: 100,
        showMessage: false
      }
    },
    {
      module: 'MMM-Tools',
      position: 'bottom_left',
      config: {}
    },
    {
      module: 'MMM-ServerStatus',
      position: 'top_left',
      header: 'Raspberry',
      config: {
        templateName: 'MyTemplate',
        group: 'raspberry',
        hosts: [
          {
            name: 'WebServer',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'SQLServer',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'Transmission',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'Lejepladsen',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'Airsonic',
            ip: 'INSERT YOURS HERE'
          }
        ],
        pingInterval: 10,
        loadDelay: 5,
        upSymbol: 'server',
        upColor: 'green',
        upText: 'is online',
        downSymbol: 'server',
        downColor: 'red',
        downText: 'is offline'
      }
    },
    {
      module: 'MMM-ServerStatus',
      position: 'top_left',
      header: 'Is home',
      config: {
        templateName: 'MyTemplate',
        group: 'mobil',
        hosts: [
          {
            name: 'My Boy',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'Me',
            ip: 'INSERT YOURS HERE'
          }
        ],
        pingInterval: 10,
        loadDelay: 10,
        upSymbol: 'mobile-alt',
        upColor: 'green',
        upText: 'is home',
        downSymbol: 'mobile-alt',
        downColor: 'red',
        downText: 'is not home'
      }
    },
    {
      module: 'MMM-ServerStatus',
      position: 'top_left',
      header: 'TV',
      config: {
        templateName: 'MyTemplate',
        group: 'TV',
        hosts: [
          {
            name: 'My Boy',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'Me',
            ip: 'INSERT YOURS HERE'
          },
        ],
        pingInterval: 10,
        loadDelay: 15,
        upSymbol: 'tv',
        upColor: 'green',
        upText: 'look tv',
        downSymbol: 'tv',
        downColor: 'red',
        downText: 'look not tv'
      }
    },
    {
      module: 'MMM-ServerStatus',
      position: 'top_left',
      header: 'Playstation',
      config: {
        templateName: 'MyTemplate',
        group: 'Playstation',
        hosts: [
          {
            name: 'My Boy',
            ip: 'INSERT YOURS HERE'
          },
          {
            name: 'Me',
            ip: 'INSERT YOURS HERE'
          }
        ],
        pingInterval: 10,
        loadDelay: 20,
        upSymbol: 'arrow-alt-circle-up',
        upColor: 'green',
        upText: 'gamer',
        downSymbol: 'arrow-alt-circle-down',
        downColor: 'red',
        downText: 'not gamer'
      }
    },
    {
      module: 'MMM-NewsFeedBerlingske',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'Berlingske',
            url: 'https://www.berlingske.dk/content/21838/rss'
          }
        ]
      }
    },
    {
      module: 'clock',
      position: 'top_center',
      config: {}
    },
    {
      module: 'compliments', /**** Is The MMM-MagicMirrorCompliments Module ****/
      position: 'bottom_bar',
      config: {
        remoteFile: 'en-compliments.json'
      }
    },
    {
      module: 'MMM-page-indicator',
      position: 'bottom_bar',
      config: {
        pages: 4,
        activeBright: true
      }
    },
    {
      module: 'MMM-GroveGestures',
      position: 'bottom_left',
      config: {
        autoStart: true,
        verbose: true,
        recognitionTimeout: 1000,
        pythonPath: '/usr/bin/python3',
        commandSet: {
          default: {
            UP: {
              moduleExec: {
                module: []
              }
            },
            DOWN: {
              moduleExec: {
                module: []
              }
            },
            LEFT: {
              notificationExec: {
                notification: 'PAGE_DECREMENT',
                payload: null
              }
            },
            RIGHT: {
              notificationExec: {
                notification: 'PAGE_INCREMENT',
                payload: null
              }
            }
          }
        }
      }
    },
    {
      module: 'MMM-pages',
      config: {
        rotationTime: 1800000,
        modules: [
          [
            'MMM-NewsFeedBT',
            'updatenotification',
            'weather',
            'MMM-DynamicWeather',
            'MMM-WeatherOrNot'
          ],
          [
            'MMM-NewsFeedEB',
            'MMM-Formula1',
	    'MMM-CountDown',
            'calendar'
          ],
          [
            'MMM-NewsFeedTV2',
            'MMM-DailyPower'
          ],
          [
            'MMM-NewsFeedBerlingske',
            'MMM-network-signal',
            'MMM-Tools',
            'MMM-ServerStatus'
          ]
        ],
        fixed: [
          'clock',
          'compliments', /**** Is The MMM-MagicMirrorCompliments Module ****/
          'MMM-page-indicator',
          'MMM-GroveGestures',
          'MMM-Remote-Control'
        ]
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: ''
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
